# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f186cb1aa94c6f959e1dad2cac4a9c6476e23e22ad5d0eb7b339dd282f2bcfee5cddfece3a3f23dfc79eddd760282647a3cff15b9b9916f40b27542171ed36

test:
  secret_key_base: 0a205835731563bb5250e08f72a191a5ecc69a53097a3568151fea5f51c9db6bf95528eafc84a796f7b53c12dad5a5c4a093713d2c0973478aede173a0d26c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
