# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36e0ce90a04fba4530ead80e50e5bba52ea9b9d3ed75129721801ec272db15ff1e9a3e8539e7b82ca865b52cb8d75266796947b52b36c18f0f6d81a116da9c6c

test:
  secret_key_base: eff26f073e11f97a73ad5da97843495574765af9cc6d10be6befccde07e0f30ce01d3204786b0c3c98786ac1b61d27fe17fdf2df1aa9d6a8f3e9842a0fd2edb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
